name: "Bug"
description: Report a defect that needs Sisu Debugging
labels: ["type:bug", "needs:sisu"]
body:
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: "User/system impact and scope"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: "Steps, logs, commit range"
    validations:
      required: true
  - type: textarea
    id: suspected
    attributes:
      label: Suspected cause
      description: "What broke and why it escaped?"
  - type: checkboxes
    id: guardrail
    attributes:
      label: Guardrail plan
      options:
        - label: "Will add a preventing test/check/limit within 48h"
          required: true
