name: "Forest Day Task"
description: Once-a-month structural improvement
labels: ["forest-day", "type:refactor"]
body:
  - type: textarea
    id: task
    attributes:
      label: Target
      description: "What we will delete, simplify, or harden"
    validations:
      required: true
  - type: input
    id: success
    attributes:
      label: Success check
      placeholder: "Metric or test proving success"
