name: Kaizen Daily
on:
  schedule:
    - cron: "0 8 * * 1-5"
  workflow_dispatch:
jobs:
  open-kaizen:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Open daily issue
        uses: actions/github-script@v7
        with:
          script: |
            const today = new Date().toISOString().slice(0,10);
            const query = `repo:${context.repo.owner}/${context.repo.repo} in:title "Kaizen ${today}"`;
            const {data} = await github.search.issuesAndPullRequests({ q: query });
            if (data.total_count === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Kaizen ${today}`,
                labels: ['type:kaizen'],
                body: "Log one slowdown and land one guardrail (<=60m)."
              });
            }
