name: Sisu Guardrail Check
on:
  pull_request:
    types: [opened, edited, synchronize, labeled]
jobs:
  sisu:
    if: contains(join(github.event.pull_request.labels.*.name, ','), 'type:bug')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            const hasSisu = /Sisu note/i.test(body);
            const hasGuardrail = /Guardrail:/i.test(body);
            if (!hasSisu || !hasGuardrail) {
              core.setFailed("Bug fix PRs must link a Sisu note and a guardrail PR.");
            }
